version: "3.7"
services:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=django
      - POSTGRESS_PASSWORD=django
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_DB=concierge
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql
  concierge:
    build: .
    user: "${uid}:${gid}"
    tty: true
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD-SHELL", "curl localhost:8000/healthcheck/ | grep OK"]
      interval: 10s
      timeout: 1s
      retries: 2
    command: "python manage.py runserver 0:8000"
    depends_on:
      - database
