# Generated by Django 3.0.2 on 2020-01-06 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='concierge.Apartment')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='KeyTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_in_date', models.DateTimeField()),
                ('key_out_date', models.DateTimeField()),
                ('key_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='concierge.Key')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='concierge.Person')),
            ],
        ),
    ]
