# Generated by Django 3.0.2 on 2020-02-13 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concierge', '0002_auto_20200212_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keytransfer',
            name='key_in_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='keytransfer',
            name='key_out_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 13, 18, 14, 9, 311258)),
        ),
    ]
