# Generated by Django 3.0.2 on 2020-02-13 18:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('concierge', '0003_auto_20200213_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keytransfer',
            name='key_out_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 13, 18, 15, 44, 208551, tzinfo=utc)),
        ),
    ]
